[project]
name = "beagle_helper"
version = "0.1.0"
authors = [
  { name="Ayush Singh", email="ayush@beagleboard.org" },
]
description = "A package to provide simple APIs for beginners"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
